[tool.poetry]
name = "rr"
version = "0.1.0"
description = ""
authors = ["muzzlol"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.4"
openai = "^1.53.0"
crawl4ai = "^0.3.72"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
